import { HeaderPhoto } from '@/lib/types';

export const headerPhotos: HeaderPhoto[] = [
	{
		src: '/images/events/hero-group.jpg',
		alt: 'Trento Cursor community group photo',
		row: 1,
		col: 1,
		rowSpan: 2,
		colSpan: 2,
		mobile: { row: 1, col: 1, rowSpan: 2, colSpan: 2 },
	},
	{
		src: '/images/events/hero-collab.jpg',
		alt: 'Workshop participants collaborating in Trento',
		row: 1,
		col: 3,
		mobile: { row: 3, col: 1 },
	},
	{
		src: '/images/events/hero-talk.jpg',
		alt: 'Community talks during an evening event',
		row: 1,
		col: 4,
		rowSpan: 2,
		mobileHidden: true,
	},
	{
		src: '/images/events/hero-pair.jpg',
		alt: 'Pair-programming session at Cafe Cursor',
		row: 2,
		col: 3,
		mobile: { row: 3, col: 2 },
	},
	{
		src: '/images/events/hero-discussion.jpg',
		alt: 'Attendees discussing product ideas',
		row: 3,
		col: 1,
		rowSpan: 2,
		mobileHidden: true,
	},
	{
		src: '/images/events/hero-builders.jpg',
		alt: 'Trento builders sharing progress',
		row: 3,
		col: 2,
		rowSpan: 2,
		colSpan: 2,
		mobileHidden: true,
	},
	{
		src: '/images/events/hero-speakers.jpg',
		alt: 'Community speakers and participants',
		row: 3,
		col: 4,
		rowSpan: 2,
		mobile: { row: 4, col: 1, colSpan: 2 },
	},
];
